ARG BASE_IMAGE
ARG BASE_IMAGE_VERSION
FROM --platform=${TARGETPLATFORM} ${BASE_IMAGE}:${BASE_IMAGE_VERSION} AS builder
WORKDIR /go/src/crd-controller
COPY . .

FROM --platform=${TARGETPLATFORM} alpine:3.17.2
COPY --from=builder /go/src/crd-controller/bin/crd-controller/usr/bin/crd-controller
CMD ["/usr/bin/crd-controller"]